name: Run Tests

on: [push]

jobs:
  test:
    name: Test on Windows
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - os: windows-latest
            rust_toolchain: stable
    steps:
      - uses: actions/checkout@v4

      - name: Setup C/C++ Compiler
        id: setup-compiler
        uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: gcc-latest

      - name: Verify CC Installation
        run: gcc --version

      - name: setup toolchain
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable

      - name: Run tests
        run: set RUST_BACKTRACE=full && cargo test test_can_compile_test_files_and_examples_on_windows_gh_action