name: Run Tests on Windows

on: [push]

jobs:
  test:
    name: Test on Windows
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - os: windows-latest
            rust_toolchain: stable
    steps:
      - uses: actions/checkout@v4

      - name: Setup C/C++ Compiler
        id: setup-compiler
        uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: gcc-latest

      - name: Verify CC Installation
        run: gcc --version

      - name: Setup toolchain
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable

      - name: Set CC env variable
        run: setx CC gcc

      - name: Enable Rust backtrace
        run: setx RUST_BACKTRACE full

      - name: Run tests
        run: cargo test